### ISSUE TITLE
Please add weight decay

### ISSUE THREAD

**Issue by sbarman-mi9** [CyberZHG/keras-radam#1]
Can you please add weight decay parameter to optimizer?

**Comment by qxde01** [comment]
tensorflow 2.0 beta
`
raise ValueError('Could not interpret optimizer identifier:', identifier)
ValueError: ('Could not interpret optimizer identifier:', <keras_radam.optimizers.RAdam `

**Comment by CyberZHG** [comment]
> tensorflow 2.0 beta
> `raise ValueError('Could not interpret optimizer identifier:', identifier) ValueError: ('Could not interpret optimizer identifier:', <keras_radam.optimizers.RAdam`

Add `TF_KERAS=1` to your environment variables.

**Comment by CyberZHG** [comment]
> Can you please add weight decay parameter to optimizer?

Done.

**Comment by qxde01** [comment]
yes,thank you
```
import os
os.environ['TF_KERAS']='1'
```
