### ISSUE TITLE
Unknown optimizer: RAdam

### ISSUE THREAD

**Issue by stvogel** [CyberZHG/keras-radam#16]
I'm currently using Keras/TF 1.12.
Model is trained with optimizer RAdam and saved.
When I load the model again with keras.models.load_model(x)
I get:
```
  File "src/models/eval_model.py", line 105, in <module>
    model = keras.models.load_model(args.model_filepath)
  File "keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "keras/engine/saving.py", line 299, in _deserialize_model
    custom_objects=custom_objects)
  File "keras/optimizers.py", line 768, in deserialize
    printable_module_name='optimizer')
  File "keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown optimizer: RAdam
```
I did an import: ```from keras_radam import RAdam```
What am I doing wrong?

**Comment by CyberZHG** [comment]
https://github.com/CyberZHG/keras-radam/blob/78dcb118c922cad0721ebed8c4a8cb6ad97cacc3/tests/test_optimizers.py#L40

**Comment by stvogel** [comment]
Dooh. Somehow I thought, this might be a dummy question.
Thanks a lot for your help!

**Comment by FrancisDacian** [comment]
> https://github.com/CyberZHG/keras-radam/blob/78dcb118c922cad0721ebed8c4a8cb6ad97cacc3/tests/test_optimizers.py#L40

Thanks.
