### ISSUE TITLE
Usage for Tensorflow 2.0 minimize with var_list

### ISSUE THREAD

**Issue by Uiuran** [CyberZHG/keras-radam#17]
Since the documentation for usage of OptimizerV2.minimize() is lacking, it is hard to realize how to use it, as the function does not query trainable_variables automatically anymore and requires var_list to be given.

My DNN to the date used TF 1.14, i would prefer to see RAdam working in it before migrating all code (production demands), or else i would give up on using it for any other scheme of adaptative learning rate.

**Comment by Uiuran** [comment]
and i think it's more for example usage rather than bug, it's only because Keras still does not provide documentation for OptimizerV2

**Comment by CyberZHG** [comment]
You don't need to know anything about `OptimizerV2` if you are using _**Keras**_.

**Comment by Uiuran** [comment]
exactly, iam not using anything of keras (except pre-build Conv2D) in my code, i dont plan to use only Keras.

**Comment by CyberZHG** [comment]
Otherwise `OptimizerV2` is the same as `tf.train.Optimizer`.

**Comment by Uiuran** [comment]
a ... unfortunately it's not, in tf2.0 it does requires var_list, but in 1.14 it doesnt.

Iam trying to downgrade your code but i got the following:
```python
RuntimeError: Override _create_vars instead of _create_slots when descending from OptimizerV2 (class RAdam)
```

**Comment by CyberZHG** [comment]
See #18, TensorFlow version of the optimizer was added in `0.8.0`:

```python
from keras_radam.training import RAdamOptimizer

RAdamOptimizer(learning_rate=1e-3)
```
