### ISSUE TITLE
Cannot start training with TensorFlow 2.0 and distribute.MirroredStrategy

### ISSUE THREAD

**Issue by makercob** [CyberZHG/keras-radam#20]
**Describe the Bug**
Cannot start training with TensorFlow 2.0 and distribute.MirroredStrategy.

**Version Info**
TensorFlow 2.0beta1
Python 3.6.8

* [ yes] I'm using the latest version

**Minimal Codes To Reproduce**

```python
strategy = tf.distribute.MirroredStrategy(devices=FLAGS.compute_devices,
           cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())

with strategy.scope():
    optimizer = RAdam(learning_rate=1e-3)
    model.compile(optimizer=optimizer, ... run_eagerly=False)
    model.fit(train_dataset)
```

<img width="1167" alt="Screen Shot 2019-08-21 at 13 34 47" src="https://user-images.githubusercontent.com/6904036/63405175-743e2600-c418-11e9-8d74-523605e39180.png">

**Comment by CyberZHG** [comment]
Try changing this line

https://github.com/CyberZHG/keras-radam/blob/7bfd0c007b900eaf6d2413c147bfcc5b8fb011e0/keras_radam/optimizer_v2.py#L65

to

```python
self._set_hyper('total_steps', float(total_steps))
```

?

**Comment by makercob** [comment]
@CyberZHG Thanks. It works. 
But it seems much slower than native optimizers.

**Comment by CyberZHG** [comment]
I think it's because the optimizer is implemented with pure python (compares to c++ & cuda).

**Comment by makercob** [comment]
my bad. Issues in my code might be the culprit of performance drop.

**Comment by makercob** [comment]
@CyberZHG Compared to native SGD optimizer, same training time consumption per epoch is observed.  Convergence is however, much much faster. Thanks!

**Comment by CyberZHG** [comment]
I've made a new release for this issue. You can upgrade to `0.7.0` if you're using `pip`.
