### ISSUE TITLE
not compatable with tf 1.8 , AttributeError: 'RAdamOptimizer' object has no attribute '_call_if_callable'

### ISSUE THREAD

**Issue by zxzxzxygithub** [CyberZHG/keras-radam#25]
**Describe the Bug**
when import tf 1.8，the console gives the error log below:

AttributeError: 'RAdamOptimizer' object has no attribute '_call_if_callable'

**Version Info**

* [x] I'm using the latest version

**Comment by CyberZHG** [comment]
😹 I'm not going to support old versions of TensorFlow.

You can try to remove these `_call_if_callable` in the `_prepare` function if you insist on using it with `tf 1.8`.

**Comment by zxzxzxygithub** [comment]
if I use way of keras,then it won't has the problem ,right?

**Comment by zxzxzxygithub** [comment]
or if it is the same 
lr = self._call_if_callable(self._lr)
with
lr = self._lr
?

**Comment by CyberZHG** [comment]
> or if it is the same
> lr = self._call_if_callable(self._lr)
> with
> lr = self._lr
> ?

I think it's the same.

**Comment by AmitRozner** [comment]
Does it support TF 1.14? I don't get any error but the accuracy is not updating. (replaced tf.train.MomentumOptimizer with RAdamOptimizer)
